### ISSUE TITLE
No documentation?

### ISSUE THREAD

**Issue by Jaafar-abusair** [venepe/react-native-mixpanel-js#1]
Hi guys,

Good job, but there is no documentations, Is this module still valid?

Thanks

**Comment by venepe** [comment]
It still works for a project I built a couple of years ago.  I would take a look at the [module it was forked](https://github.com/danscan/rn-redux-mixpanel) from though.  It still looks active.  You can also take a look at [how it was used](https://github.com/venepe/describe-react-native/blob/054e542a063c1f53850eb52b5a372e356c644788/lib/SMTIAnalytics.js#L49)
